### ISSUE TITLE
"Header too small"

### ISSUE THREAD

**Issue by paulamartingonzalez** [EGA-archive/crypt4gh#29]
Hi! I am trying to decrypt some files and I have a secret key for that that I've set as passphrase:

`export C4GH_PASSPHRASE= decryption key they sent me via email`

I am trying to generate a secret key using `ssh-keygen -t ed25519` and then I set this: 

`export C4GH_SECRET_KEY=’ega_ed25519_key' generated as above`

But when I try to decrypt my file using `cat $file_to_decrypt | crypt4gh decrypt > "$file_to_decrypt"`

I get the error: 

```
Warning: Using a passphrase in an environment variable is insecure
Header too small
```

Do you know where the error is coming from? Many thanks in advance!

**Comment by silverdaz** [comment]
Hi Paula,

You don't need to _generate_ a key to decrypt an _already_ encrypted file. That key wouldn't be adapted for that file.

Do you have the decryption key?

Who sent you a passphrase? If so, they might have sent you the decryption key. In that case, pass it with the flag `--sk` (or with the env variable `C4GH_SECRET_KEY`). You'll get prompted for the passphrase (or use the env variable `C4GH_PASSPHRASE`)

If you don't have the decryption key, there isn't much to do...

**Comment by silverdaz** [comment]
Closing that issue as there is not enough information to help on that issue. Please re-open it when you have more.
