### ISSUE TITLE
I can't install it

### ISSUE THREAD

**Issue by AlexanderSenf** [EGA-archive/crypt4gh#3]
pip install git+https://github.com/EGA-archive/crypt4gh.git
Collecting git+https://github.com/EGA-archive/crypt4gh.git
  Cloning https://github.com/EGA-archive/crypt4gh.git to /tmp/pip-req-build-zze_dA
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-zze_dA/setup.py", line 23
        f'{PROG} = crypt4gh.__main__:main' ,
                                         ^
    SyntaxError: invalid syntax
    
    ----------------------------------------

This is on:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

**Comment by omllobet** [comment]
Could you check the python version? It should be python 3.7

```
pip --version
pip 18.1 from /home/martini/.pyenv/versions/3.7.1/lib/python3.7/site-packages/pip (python 3.7)
```

**Comment by AlexanderSenf** [comment]
pip --version
pip 18.1 from /home/asenf/.local/lib/python2.7/site-packages/pip (python 2.7)

Aha! Python 2.7. I will update and try again

**Comment by AlexanderSenf** [comment]
I just can't get around this (it also happens on Ubuntu 14.05.5 LTS / Python 3.4.3) :

  File "setup.py", line 23
    f'{PROG} = crypt4gh.__main__:main' ,
                                     ^
SyntaxError: invalid syntax

**Comment by AlexanderSenf** [comment]
The issue may be that I am using Python 3.4 / 3.5. f-String only work with Python 3.6+

**Comment by blankdots** [comment]
@AlexanderSenf  install one of: 
* https://virtualenv.pypa.io/en/latest/ 
* https://github.com/pyenv/pyenv 
* https://pipenv.readthedocs.io/en/latest/

with Python3.6

**Comment by blankdots** [comment]
> File "setup.py", line 23
f'{PROG} = crypt4gh.main:main' ,
^
SyntaxError: invalid syntax

That error is related to f strings which are 3.6+

**Comment by AlexanderSenf** [comment]
Thank you ! :) This worked, on a brand new Ubuntu 16.04 LTS VM:

sudo apt-get update
sudo apt-get install -y software-properties-common curl
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt-get update 
sudo apt-get install -y python3.6 python3.6-venv

mkdir environments
cd environments

virtualenv --python=python3.6 myvenv
source myvenv/bin/activate

pip install pynacl
pip install paramiko

pip install git+https://github.com/EGA-archive/crypt4gh.git

**Comment by blankdots** [comment]
@AlexanderSenf good :+1: 
I made this comment https://github.com/EGA-archive/crypt4gh/issues/3#issuecomment-459001744 before seeing this: https://github.com/EGA-archive/crypt4gh/issues/3#issuecomment-458946881 

@silverdaz maybe we should add such instructions to the installation setup, also these might be good for LocalEGA as well

**Comment by silverdaz** [comment]
Sure. That's on the "roadmap".
Wanna give a hand?

PS: do leave LocalEGA out of this.

**Comment by silverdaz** [comment]
Closing this issue as it is not an issue anymore.
