### ISSUE TITLE
No supported encryption method

### ISSUE THREAD

**Issue by christophechu** [EGA-archive/crypt4gh#38]
crypt4gh decrypt --sk ~/.ssh/chut_mac.sec < ***.c4gh                                                

No supported encryption method

**Comment by silverdaz** [comment]
Closing the issue as there is no answer. Re-open it if needed

**Comment by MixalisSn** [comment]
Although I have successfully decrypted over 160 files now, in the last 20, I am experiencing the same error message. 
What could be the problem?

**Comment by silverdaz** [comment]
Ping @sdelatorrep and @omllobet: Can you give a hand?

**Comment by MixalisSn** [comment]
I found out that the files should have been downloaded with the same public/private key pair with which they are decrypted. Otherwise, this error occurs.
Thank you @silverdaz!
