### ISSUE TITLE
FileZilla does not recognize Crypt4GH private key

### ISSUE THREAD

**Issue by SuhasSrinivasan** [EGA-archive/crypt4gh#43]
Dear EGA Team,

When trying to follow the EGA Live Outbox [guidelines](https://ega-archive.org/access/download/files/live-outbox/), FileZilla does not recognize the Crypt4GH private key (.sec).
`The file could not be loaded or does not contain a private key.`

This issue also occurs when using the **ed25519** SSH key pair.

There does not appear to be any FileZilla documentation about which types of keys are supported.

Your input would be helpful.

**Comment by silverdaz** [comment]
Hi FileZilla only uses SSH keys to _login_. There is no Crypt4GH going on in FileZilla.

On the other hand, this Crypt4GH implementation _can_ use the SSH-ed25519 keys (along with its own key format), to handle the encryption/decryption.
 
As for the ssh-ed25519 key in FileZilla, maybe you can check if your version supports it.
If I remember correctly, FileZilla converts all keys to its own `.ppk` format anyway.

Also note that this repo is about the python implementation for Crypt4GH, not about the EGA Live Outbox.
Please contact the [EGA helpdesk](https://ega-archive.org/need-help/) for further inqueries regarding the EGA Live Outbox.
I'm therefore closing this issue.
