### ISSUE TITLE
Tests are commented out

### ISSUE THREAD

**Issue by wandergeek** [EGA-archive/crypt4gh#6]
Most of the tests in `test_crypt4gh.py` and `test_cli.py` are commented out. As we start collaborating on this together, we could be breaking things and not know it. Would be great if we can get these working again! 👍

**Comment by blankdots** [comment]
Tests are in the works. I don't have an estimate yet on when.

**Comment by silverdaz** [comment]
There are new tests now, using [BATS](https://github.com/bats-core/bats-core).
The testsuite is easily extendable.
